### ISSUE TITLE
Spreadsheet editor don't open

### ISSUE THREAD

**Issue by brianmsm** [jasp-stats/jasp-issues#1045]
* JASP version: 0.14

* OS name and version: Manjaro 20.2 GNU/Linux
* Analysis: This situation happens with all files that I test it. Include, the example files.
* Bug description: Whatever file .csv don't open spreadsheet editor when I click on cells.
* Expected behaviour: When I click on cells, an spreadsheet edito should open, like libreoffice (it's default editor in my system).

**Comment by JorisGoosen** [comment]
Hello Brian,

Sorry to hear the spreadsheeteditor isn't opening.
Could I ask what desktop environment you are using?

**Comment by brianmsm** [comment]
I currently using KDE Plama 5.20

**Comment by JorisGoosen** [comment]
Aah so this problem doesn't just affect @vandenman..

I'm trying to get a beta-build of flatpak up and running where the spreadsheeteditor will actually open on Plasma.
I'll post here if I manage to get that compiled.

**Comment by vandenman** [comment]
@JorisGoosen actually, the problem is solved with the latest flatpak release. I'm on Ubuntu 18.04 though with plasma 5.12.9

**Comment by JorisGoosen** [comment]
@vandenman which version of flatpak are you on now?
And @brianmsm ?
`flatpak --version`

**Comment by vandenman** [comment]
```
flatpak --version       
Flatpak 1.8.2

flatpak list | grep JASP
JASP    org.jaspstats.JASP      0.13.1  beta    flathub-beta    system
JASP    org.jaspstats.JASP      0.14.1  stable  flathub system
```

**Comment by brianmsm** [comment]
I would assume that with Manjaro I would have the most up to date version of flatpak. It seems that it is not so.

```
flatpak --version
Flatpak 1.8.1

flatpak list | grep JASP
JASP    org.jaspstats.JASP      0.14.1  stable  system
```
So, Do I need to upgrade my version of flatpak?

**Comment by brianmsm** [comment]
I've just upgraded my version of flatpak from arch's repos, but the issue is still here.

```
flatpak --version
Flatpak 1.8.2

flatpak list | grep JASP
JASP    org.jaspstats.JASP      0.14.1  stable  system
```

**Comment by tomtomme** [comment]
I can confirm this. Also setting a text editor like kate to handle csv does not help. It worked with JASP 0.13 the last time I think. 
I am also on manjaro KDE.
@brianmsm How did you update your flatpak to 1.8.2? There is only 1.8.1 in my list.

**Comment by brianmsm** [comment]
I downloaded the package from here: https://www.archlinux.org/packages/extra/x86_64/flatpak/download/

**Comment by JorisGoosen** [comment]
Yeah it is too bad but it seems to be caused by `Plasma` in combination with our version of Qt (still using 5.12 atm)...
If you run any other desktop environment the spreadsheet editor *will* open...

**Comment by tomtomme** [comment]
Thanks. I installed it successfully. That did not help me either. But I did notice: 
If the file comes from /app/bin/Resources/Data Sets/Data Library/...
then - and only then - I can edit the file. However I do have no clue where this folder really is. Its not accessible with my filemanager. But the path is shown this way in jasp.

**Comment by JorisGoosen** [comment]
Ooh that is weird!

`/app/bin` is a fake root folder flatpak makes to run software from. This is actually (for jasp anyway) not real files but sort of a git-repo for files so it isn't really possible to find it normally.

The strange thing is that those files are the bundled datafiles and are the only ones that aren't supposed to be editable...

**Comment by tomtomme** [comment]
I can open them as .jasp - then I cannot edit, but he asks first to create a datafile. That I can only create in an "outside" folder. So no edit possiple.
But when I open it as .csv from the datalibrary I can edit. He asks me first which program to use and then I select the editor and it opens it "write protected". However I can make it writable with a press of a button in libreoffice calc. When I want to save changes however, I have to safe to a different folder and am back to square one. A file that is edited once, but can't be edited further, cause its in another folder.

**Comment by JorisGoosen** [comment]
Ah yeah ok, that is less weird then.

Well I will try to have this fixed for the upcoming 0.14.1 release (although I see in flatpak I already accidentally gave the latest version that number) .

In the meantime the workaround (when you do not want to switch desktop environment) is that you could just open the spreadsheet-editor separately and open your csv file. JASP will still sync with it even if it didn't open the spreadsheeteditor itself.

**Comment by tomtomme** [comment]
good to know!!

**Comment by JorisGoosen** [comment]
Maybe someone who is having some trouble opening the spreadsheet editor on linux with JASP 0.14 can help me out by testing the new beta release of JASP?

To do so you need to add `flathub-beta` as follows:
`flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`

And then you can install the jasp beta like: `flatpak install flathub-beta org.jaspstats.JASP`

To run the beta version start jasp like `flatpak run --branch=beta org.jaspstats.JASP`.
Flatpak will remember you started the beta so from now on it will start the beta until you start the normal jasp at least once with:
`flatpak run --branch=stable org.jaspstats.JASP`

**Comment by tomtomme** [comment]
It works!!!!
Tried with a .csv and edited in libreoffice.
Tried with a .sav and edited in pspp.
Nice work :+1:

**Comment by tomtomme** [comment]
I hit a snag. When I want to analyse any edited data file now jasp crashes. I just hit the button "descriptives" and its gone. This is for all file types and only with edited files. Its also for all analysis buttons, for some it just needs some seconds before it crashes.

last lines in konsole are: 

```
So the entire column had a change? yes

qrc:/components/JASP/Widgets/AnalysisFormExpander.qml:429:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

Created Write Seal for jaspResults at: '/home/thomasl/.JASP/temp/2/resources/0/jaspResultsFinishedWriting.txt' 
```
then crash

**Comment by JorisGoosen** [comment]
> I tried with a .ods now. The sync to jasp did not work the first time. The sync popup in jasp just stayed there. No edit was shown. On closing everything and reopening jasp crashed. On a second try then everything worked, also the sync.
> It seems to be reproducible: If I have only one variablename and one number / case - and when I delete that single case, leaving an empty variable, then the sync to jasp does not work and it crashes later. This is however a very edge case and applies only to .ods files, so I would not mind if this is a no fix, maybe even a problem on the libreoffice-side.

This might be an unknown issue, Ive certainly never seen it. You could make a new issue for that, but be careful to mention you've used the flatpak beta.

**Comment by JorisGoosen** [comment]
> Probably this is a new issue?
> 
> I hit a snag. When I want to analyse any data file now jasp crashes. I just hit the button "descriptives" and its gone. This is for all file types from any location and all analysis buttons, for some it just needs some seconds before it crashes. First I thought its only for edited files, but also those from the data library crash jasp after some more seconds.

Well, it is a beta version, although we honestly didn't change that much so Im a bit surprised. Would you be interested in helping us test the next release? I could add you to our "External Testers" team and you would then be granted access to the testing issue tracker. Where we could then make a new issue for this. Otherwise it would also be fine to make a new issue for it here in jasp-issues.

**Comment by tomtomme** [comment]
> > Probably this is a new issue?
> > I hit a snag. When I want to analyse any data file now jasp crashes. I just hit the button "descriptives" and its gone. This is for all file types from any location and all analysis buttons, for some it just needs some seconds before it crashes. First I thought its only for edited files, but also those from the data library crash jasp after some more seconds.
> 
> Well, it is a beta version, although we honestly didn't change that much so Im a bit surprised. Would you be interested in helping us test the next release? I could add you to our "External Testers" team and you would then be granted access to the testing issue tracker. Where we could then make a new issue for this. Otherwise it would also be fine to make a new issue for it here in jasp-issues.

Thanks, I would like to beta-test and report issues :D

**Comment by JorisGoosen** [comment]
Ok @tomtomme Ive added you to the group and made an issue for the jasp crash: https://github.com/jasp-stats/jasp-test-release/issues/1054

Im guessing the crash on ods is related to the crash on running an analysis... But we'll have to see what is going wrong.

This issue is solved at least so Ill close it.

**Comment by tomtomme** [comment]
the above link leads to a 404 page...

**Comment by JorisGoosen** [comment]
> the above link leads to a 404 page...

Have you accepted the invitation to the external testers team in jasp-stats?
Then you should be granted access there (if logged in ofc)

**Comment by tomtomme** [comment]
That invitation was a bit hidden. Thx for the tip. Got it now.
