### ISSUE TITLE
[Bug]: Compilation fails on Linux, missing #include (I guess).

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1594]
### JASP Version

Current `development` branch.

### Commit ID

72cead0afe63a628d353704b5a3d0bf278855c0a

### What analysis are you seeing the problem on?

jaspDesktop

### What OS are you seeing the problem on?

Arch Linux

### Bug Description

I tried to compile current `development` branch with g++ (GCC) 11.1.0.

It fails due to 3 `std` functions `isnan`, `isfinite`, and `round`, see logs below.

It's easy to fix by adding `#include <cmath>` into `Desktop/widgets/textinputbase.h` and `Engine/rbridge.h`, for example.
Probably there is a more elegant/correct way to fix it.
But I have no real idea what I'm doing, so I'm not offering a PR.
Let me know if I can help somehow.

### Expected Behaviour

Compile without errors.

### Steps to Reproduce

1. Check out `development`.
2. Run `make`, or build in QtCreator.

### Log (if any)

```bash
jasp-desktop/Engine/rbridge.cpp:497: error: ‘isnan’ is not a member of ‘std’
../../jasp-desktop/Engine/rbridge.cpp:497:50: error: ‘isnan’ is not a member of ‘std’
  497 |                                         if (std::isnan(value))
      |                                                  ^~~~~

[...]

jasp-desktop/Engine/rbridge.cpp:502: error: ‘isfinite’ is not a member of ‘std’
../../jasp-desktop/Engine/rbridge.cpp:502:50: error: ‘isfinite’ is not a member of ‘std’
  502 |                                         if (std::isfinite(value))       intValue = (int)(value * 1000);
      |                                                  ^~~~~~~~

[...]

jasp-desktop/Desktop/widgets/textinputbase.cpp:92: error: ‘round’ was not declared in this scope; did you mean ‘qRound’?
../../jasp-desktop/Desktop/widgets/textinputbase.cpp: In member function ‘virtual void TextInputBase::bindTo(const Json::Value&)’:
../../jasp-desktop/Desktop/widgets/textinputbase.cpp:92:35: error: ‘round’ was not declared in this scope; did you mean ‘qRound’?
   92 |                         dblVal = (round(dblVal * pow))/pow;
      |                                   ^~~~~
      |                                   qRound

[...]

make[1]: Leaving directory 'jasp-build/Desktop'
make: *** [Makefile:102: sub-Desktop-make_first] Error 2
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
If I recall correctly, this is fixed in the branch that I'm working on, but that's not yet in the development. Our headers usage is not that clean, and as compilers are getting more strict about this, we ran into situations like this. For now, I believe adding the `#include <cmath>` to `textinputbase.cpp`, and `rbridge.cpp` will resolves this.

P.S. I have integrated the [`include-what-you-use`](https://github.com/include-what-you-use/include-what-you-use) in our new build system, and after a few iterations we should catch most of these, and have a faster build as a result.

**Comment by JoKeyser** [comment]
@amirmasoudabdol thanks for checking this out; sounds all good to me, happy to test when your branch lands.

**Comment by rhuhle** [comment]
I'm trying to compile it in arch as well. Could anyone give me a hint which packages are must haves. 

For me make (recent Arch, x86_64, gcc 11.2.0, qt5.15.2) is failing with missing headers e.g.:
jasp-desktop/Common/column.h:31:10: fatal error: columntype.h: No such file or directory

**Comment by JoKeyser** [comment]
@rhuhle I haven't tried since I opened this issue, but afaik, the principal documentation about building is https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md#linux. That may be outdated, and if so, it would be great to update/improve it. I haven't look at it in many months. (As this issue proves, the branch state is not always compilable out of the box, so only dig as deep as you want/have time. Sorry for the inconclusive answer, maybe somebody else will answer more substantially.)

**Comment by rhuhle** [comment]
Thanks Jo for the link. Infact I had forgotten to clone into the submodules.

After changing the includes above I have the issue now with a qt error:
Project ERROR: Unknown module(s) in QT: webenginequick core5compat

Which leads me to the question which qt packages you have installed when you successfully build jasp-desktop on Arch!?

**Comment by vandenman** [comment]
@rhuhle you should have these packages installed:
![image](https://user-images.githubusercontent.com/21319932/156579814-7311bb93-5f53-4aa5-9b54-47e9a76415f8.png)

**Comment by sukanka** [comment]
> jasp-desktop/Common/column.h:31:10: fatal error: columntype.h: No such file or directory

I have the same issue, and I find it is in https://github.com/jasp-stats/jaspColumnEncoder/tree/aaacc69dc8cb3eb86affa8795c2ec523af3aefd1
so, the released tarball doesn't contain these files. We cannot build from the released tarball.

**Comment by vandenman** [comment]
It is indeed necessary to manually check out the submodules. This is arguably not a bug in Jasp, but rather GitHub because they do not support this (see e.g., this [feature request](https://github.community/t/create-release-that-contains-submodule/1329) on GitHub's own forum). Happy to hear you got Jasp to build though, in case you need any help with the runtime errors, feel free to send us a message or open an issue. Also, like with the conda distribution of Jasp, I'd recommend following the approach we use on flatpak and using the tar.gz with R package sources for a particular release to avoid any errors being introduced by system updates.

**Comment by sukanka** [comment]
> It is indeed necessary to manually check out the submodules.

Well I know that, it's Github's fault.

> Happy to hear you got Jasp to build though, in case you need any help with the runtime errors, feel free to send us a message or open an issue. 

Thanks for your enthusiasm, I know what I'm doing now. The runtime error has nothing to do with jasp itself, it is because  I
changed the paths, for example `Modules` are moved to `/usr/lib/jasp-desktop`, and `Resources` are moved to `/usr/share/jasp-desktop`. So I have to edit the source code of `jasp-desktop` accordingly.

> Also, like with the conda distribution of Jasp, I'd recommend following the approach we use on flatpak and using the tar.gz with R package sources for a particular release to avoid any errors being introduced by system updates.

That's definitely correct! But I prefer to rebuild the package when there is an error introduced by system updates.

**Comment by sukanka** [comment]
Hi, I'm glad to announce that I have just successfully build `jasp-desktop` on archlinux, with system R, and other r packages.
If you are interested in this, you can have a look at [jaspOnArch](https://github.com/sukanka/jaspOnArch).
The only todo is to run some test scripts if there are any.

**Comment by JoKeyser** [comment]
@sukanka that sounds great; maybe you are considering to make this available in the AUR, if that makes sense? (I'm not super familiar with Arch packaging.)

**Comment by sukanka** [comment]
> @sukanka that sounds great; maybe you are considering to make this available in the AUR, if that makes sense? (I'm not super familiar with Arch packaging.)

Right, I plan to do this (and also add it to BioArch repository), but I'm now running into problems. The application runs fine except for plots. When I tried to add some plots, it gave me a warning `Graphics API version mismatch` instead of the graph. 
So still a lot of things to do. A relevant issue is https://github.com/jasp-stats/jasp-issues/issues/1722

**Comment by vandenman** [comment]
> The only todo is to run some test scripts if there are any.

Before each release, we run `jasp --unitTestRecursive Resources/Data\ Sets/Data\ Library/`, which refreshes all jasp files in the data library and tests if anything changes. This doesn't make much sense before `Graphics API version mismatch` is fixed though (but let's discuss that in the dedicated issue).

**Comment by sukanka** [comment]
> > The only todo is to run some test scripts if there are any.
> 
> Before each release, we run `jasp --unitTestRecursive Resources/Data\ Sets/Data\ Library/`, which refreshes all jasp files in the data library and tests if anything changes. This doesn't make much sense before `Graphics API version mismatch` is fixed though (but let's discuss that in the dedicated issue).

Hi! thanks for your suggestion! I'm running (no `--hide` as I have to manually close some tests, because jasp seems not to do anything in these tests)
```
 jasp --unitTestRecursive '/usr/lib/jasp-desktop/Resources/Data Sets/Data Library/' \
    --logToFile
```
The result is 
> Finished running test, 17 out of 79 jasp files FAILED!

A typical failure is like this, I'm not sure whether it is because of randomness (different version of R may generate different random numbers even if the same seed is used, I guess)

Another issue I noticed is when jasp stops, there is a warning
```
QProcess: Destroyed while process ("/usr/lib/jasp-desktop/bin/JASPEngine") is still running.
```
At first, I'm not worried about this,  but during the test, I noticed there are 91 JASPEngines that do not die out after the test procedure, each consuming about 260MiB to 400MiB memory. I almost run of out my memory in this test.

So I also need to deal with this issue.

### Detailed test results
```
The results are different...
Tables:
        Tables are the same

        Header:
                Table sections are the same

        Body:
                Rows:
                        Row: | H1 |  | 7.492e-20 |  | 7.492e-20 |  | 2.072e-20 != 2.278e-20 |  | 1.623e-20 != 1.747e-20 |  | 1.687e-20 != 1.813e-20 |  | 
                        Row: | H2 |  | 3.617 != 3.288 |  | 4.391 != 3.892 |  | 1.000 |  | 0.783 != 0.767 |  | 0.814 != 0.796 |  | 
                        Row: | Hu |  |  |  |  |  |  |  | 0.217 != 0.233 |  |  |  | 
                        Row: | Hc |  | 0.824 != 0.845 |  |  |  |  |  |  |  | 0.186 != 0.204 |  | 
                        Rows are the same

        Footer:
                Table sections are the same


        Header:
                Table sections are the same

        Body:
                Rows:
                        Row: | H1 |  | 1.000 |  | 2.072e-20 != 2.278e-20 |  | 
                        Row: | H2 |  | 4.827e+19 != 4.389e+19 |  | 1.000 |  | 
                        Rows are the same

        Footer:
                Table sections are the same


        Tables are the same




JASP file /usr/lib/jasp-desktop/Resources/Data Sets/Data Library/8. Bain/bainRegression.jasp failed!
```
And like this 
```
The results are different...
Tables:
        Tables are the same

        Header:
                Table sections are the same

        Body:
                Rows:
                        Row: | H1 |  | 1.151e-11 |  | 1.151e-11 |  | 1.633e-13 != 1.670e-13 |  | 1.610e-13 != 1.646e-13 |  | 1.624e-13 != 1.660e-13 |  | 
                        Row: | H2 |  | 70.519 != 68.948 |  | 177.182 != 170.291 |  | 1.000 |  | 0.986 |  | 0.994 |  | 
                        Rows are the same
                        Row: | Hc |  | 0.398 != 0.405 |  |  |  |  |  |  |  | 0.006 |  | 
                        Rows are the same

        Footer:
                Table sections are the same


        Header:
                Table sections are the same

        Body:
                Rows:
                        Row: | H1 |  | 1.000 |  | 1.633e-13 != 1.670e-13 |  | 
                        Row: | H2 |  | 6.124e+12 != 5.988e+12 |  | 1.000 |  | 
                        Rows are the same

        Footer:
                Table sections are the same


        Tables are the same




JASP file /usr/lib/jasp-desktop/Resources/Data Sets/Data Library/8. Bain/bainAnova.jasp failed!
```
Also this 
```
The results are different...
Tables:
        Header:
                Table sections are the same

        Body:
                Rows:
                        Row: | 1 |  | RaceVictim + RaceDefendant + Death + RaceVictim✻RaceDefendant + RaceVictim✻Death |  | 0.495 != 0.509 |  | 1.000 |  | 
                        Row: | 2 |  | RaceVictim + RaceDefendant + Death + RaceVictim✻RaceDefendant + RaceVictim✻Death + RaceDefendant✻Death |  | 0.408 != 0.406 |  | 1.212 != 1.256 |  | 
                        Row: | 3 |  | RaceVictim + RaceDefendant + Death + RaceVictim✻RaceDefendant + RaceVictim✻Death + RaceDefendant✻Death + RaceVictim✻RaceDefendant✻Death |  | 0.096 != 0.085 |  | 5.183 != 5.994 |  | 
                        Row: | 4 !=  |  != missing | RaceVictim + RaceDefendant + Death + RaceVictim✻RaceDefendant != missing |  != missing | 0.001 != missing |  != missing | 495.000 != missing |  != missing | 
                        Row is missing in new table section

        Footer:
                Rows:
                        Row: | Note.Total number of models visited = 4 != Note.Total number of models visited = 3 | 




[1808099:1808144:0531/102828.327985:ERROR:gl_context_glx.cc(230)] Couldn't make context current with X drawable.
[1808099:1808144:0531/102828.328056:ERROR:skia_output_surface_impl_on_gpu.cc(1563)] Failed to make current.

JASP file /usr/lib/jasp-desktop/Resources/Data Sets/Data Library/5. Frequencies/Death Penalty.jasp failed!
```

**Comment by vandenman** [comment]
> At first, I'm not worried about this, but during the test, I noticed there are 91 JASPEngines that do not die out after the test procedure, each consuming about 260MiB to 400MiB memory. I almost run of out my memory in this test.

I have no experience with engines behaving like this, but perhaps @JorisGoosen does? This certainly doesn't sound good.

Also, since you're comparing the unreleased version to the old release, it's certainly possible that some output changed. 17 out of 79 failures may look like a lot, but these tests don't compare the values in the tables against a tolerance but rather absolutely (e.g., 1.633e-13 != 1.670e-13 is a meaningless change because in R `all.equal(1.633e-13, 1.670e-13)` returns `TRUE`. The other differences look indeed look like differences due to the seed.

**Comment by sukanka** [comment]
> Also, since you're comparing the unreleased version to the old release, it's certainly possible that some output changed. 17 out of 79 failures may look like a lot, but these tests don't compare the values in the tables against a tolerance but rather absolutely (e.g., 1.633e-13 != 1.670e-13 is a meaningless change because in R `all.equal(1.633e-13, 1.670e-13)` returns `TRUE`. The other differences look indeed look like differences due to the seed.

I also built jasp 0.16.2 and all modules pinned at  the commits in jasp 0.16.2 release. Some tests still fail.
Perhaps the above tests results are produced by JASP 0.16.2. I forgot it.

So I guess these results are caused by the underlying R packages.

**Comment by sukanka** [comment]
> @sukanka that sounds great; maybe you are considering to make this available in the AUR, if that makes sense? (I'm not super familiar with Arch packaging.)

Glad to announce that we have make `jasp-desktop` available in [BioArchLinux](https://github.com/BioArchLinux/Packages)
But it is extremely hard to make it available on AUR, as many dependencies (R packages) are not in AUR. (I'm still thinking about this)
So such a package in AUR only reminds the user that there is `jasp-desktop` in BioArchLinux, and he should add that repository to his `pacman.conf`

**Comment by tomtomme** [comment]
I just added the repo using instructions here: https://github.com/BioArchLinux/Packages
Then tried 
`sudo pacman -Syyu jasp-desktop`

This complains about missing deps.
How can I tell pacman to use the BioArch-Repo which includes the deps?
Or am I doing something wrong?
I am a Arch-Noob (manjaro-user)

**Comment by sukanka** [comment]
> I just added the repo using instructions here: https://github.com/BioArchLinux/Packages Then tried `sudo pacman -Syyu jasp-desktop`
> 
> This complains about missing deps. How can I tell pacman to use the BioArch-Repo which includes the deps? Or am I doing something wrong? I am an Arch-noob (manjaro-user)

After adding the repo, please run `pacman -Syy` to update the databases, and then run 
```
sudo pacman -S jasp-desktop
```
I'm not clear whether  `Syyu` will work.

**Comment by tomtomme** [comment]
I guess I have a manjaro specific problem then. These are the missing deps he complains about:

```
[tom@tomspc ~]$ sudo pacman -S jasp-desktop
Abhängigkeiten werden aufgelöst …
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-kernsmooth" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-jaspanova" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-mgcv" nicht auflösen (eine Abhängigkeit von "r-jaspmixedmodels")
Warnung: Kann "r-jaspmixedmodels" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspregression")
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-kernsmooth" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-jaspanova" nicht auflösen (eine Abhängigkeit von "r-jaspregression")
Warnung: Kann "r-jaspregression" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-stats" nicht auflösen (eine Abhängigkeit von "r-jaspbain")
Warnung: Kann "r-jaspbain" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-mass" nicht auflösen (eine Abhängigkeit von "r-jaspmetaanalysis")
Warnung: Kann "r-jaspmetaanalysis" nicht auflösen (eine Abhängigkeit von "r-jaspcochrane")
Warnung: Kann "r-jaspcochrane" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-grid" nicht auflösen (eine Abhängigkeit von "r-jasplearnbayes")
Warnung: Kann "r-grdevices" nicht auflösen (eine Abhängigkeit von "r-jasplearnbayes")
Warnung: Kann "r-jasplearnbayes" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-cluster" nicht auflösen (eine Abhängigkeit von "r-jaspmachinelearning")
Warnung: Kann "r-jaspmachinelearning" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-mass" nicht auflösen (eine Abhängigkeit von "r-jaspmetaanalysis")
Warnung: Kann "r-jaspmetaanalysis" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-mass" nicht auflösen (eine Abhängigkeit von "r-jaspreliability")
Warnung: Kann "r-jaspreliability" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspregression")
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-kernsmooth" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-jaspanova" nicht auflösen (eine Abhängigkeit von "r-jaspregression")
Warnung: Kann "r-jaspregression" nicht auflösen (eine Abhängigkeit von "r-jaspsummarystatistics")
Warnung: Kann "r-boot" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-kernsmooth" nicht auflösen (eine Abhängigkeit von "r-jaspanova")
Warnung: Kann "r-jaspanova" nicht auflösen (eine Abhängigkeit von "r-jaspsummarystatistics")
Warnung: Kann "r-jaspsummarystatistics" nicht auflösen (eine Abhängigkeit von "jasp-desktop")
:: Das folgende Paket kann aufgrund nicht auflösbarer Abhängigkeiten nicht aktualisiert werden:
      jasp-desktop

:: Möchten Sie das oben genannte Paket bei dieser Aktualisierung überspringen? [j/N] j
Nach in Konflikt stehenden Paketen wird gesucht …
 Es gibt nichts zu tun
```

For info: 
```
[tom@tomspc ~]$ cat /etc/pacman.conf
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
CacheDir = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg      = pacman glibc manjaro-system
# If upgrades are available for these packages they will be asked for first
SyncFirst    = manjaro-system archlinux-keyring manjaro-keyring
#XferCommand = /usr/bin/curl -C - -f %u > %o
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

#IgnorePkg   =
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
#Color
#TotalDownload
# We cannot check disk space from within a chroot environment
CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Manjaro Linux
# packagers with `pacman-key --populate archlinux manjaro`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

[core]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[community]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

[bioarchlinux]
Server = https://repo.bioarchlinux.org/$arch
```

I also did
```
$ pacman-key --recv-keys B1F96021DB62254D
$ pacman-key --finger B1F96021DB62254D
$ pacman-key --lsign-key B1F96021DB62254D
```

**Comment by sukanka** [comment]
> I guess I have a manjaro specific problem then. These are the missing deps he complains about 

Have a look at this. r in archlinux repo now provides r-boot and other r modules. 

https://archlinux.org/packages/community/x86_64/r/

**Comment by tomtomme** [comment]
While it finished downloading, it now complains of file conflicts:
```
(580/580) Auf Dateikonflikte wird geprüft                                                                                    [###########################################################################] 100%
Fehler: Der Vorgang konnte nicht durchgeführt werden (In Konflikt stehende Dateien)
python-docutils: /usr/bin/rst2html.py existiert im Dateisystem
python-docutils: /usr/bin/rst2html4.py existiert im Dateisystem
python-docutils: /usr/bin/rst2html5.py existiert im Dateisystem
python-docutils: /usr/bin/rst2latex.py existiert im Dateisystem
python-docutils: /usr/bin/rst2man.py existiert im Dateisystem
python-docutils: /usr/bin/rst2odt.py existiert im Dateisystem
python-docutils: /usr/bin/rst2odt_prepstyles.py existiert im Dateisystem
python-docutils: /usr/bin/rst2pseudoxml.py existiert im Dateisystem
python-docutils: /usr/bin/rst2s5.py existiert im Dateisystem
python-docutils: /usr/bin/rst2xetex.py existiert im Dateisystem
python-docutils: /usr/bin/rst2xml.py existiert im Dateisystem
python-docutils: /usr/bin/rstpep2html.py existiert im Dateisystem
Fehler sind aufgetreten, keine Pakete wurden aktualisiert.

```

**Comment by sukanka** [comment]
> While it finished downloading, it now complains about file conflicts:
> 
> ```
> (580/580) Auf Dateikonflikte wird geprüft                                                                                    [###########################################################################] 100%
> Fehler: Der Vorgang konnte nicht durchgeführt werden (In Konflikt stehende Dateien)
> python-docutils: /usr/bin/rst2html.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2html4.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2html5.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2latex.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2man.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2odt.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2odt_prepstyles.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2pseudoxml.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2s5.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2xetex.py existiert im Dateisystem
> python-docutils: /usr/bin/rst2xml.py existiert im Dateisystem
> python-docutils: /usr/bin/rstpep2html.py existiert im Dateisystem
> Fehler sind aufgetreten, keine Pakete wurden aktualisiert.
> ```

Did you used `sudo pip` to install python packages? If so I guess you can simply use 

`sudo pacman -S python-docutils --asdeps --overwrite='/usr/*'`
to overwrite it. And do not install packages via sudo pip any more.

**Comment by tomtomme** [comment]
This worked! Very nice and thank you very much! Now I have a native jasp-build in manjaro without the flatpak-pains I had in the past. And it is even the 0.16.2 build that would not work on linux before, when flatpacked - how did you do that?

![grafik](https://user-images.githubusercontent.com/4428185/174031893-a771dda7-3306-4740-b575-8276d0cbd280.png)

**Comment by JorisGoosen** [comment]
The version 0.16.2 always compiled fine on linux, we just had some trouble integrating (due to webengine being separated from qt6) the new buildsystem with flatpak. Which we've done now though for 0.16.3

But also very nice to have a native build on arch/manjaro ^^

**Comment by tomtomme** [comment]
I updated on my main machine to 0.16.3 just fine.
Now I try to install fresh on my laptop and get: 
```
Erstelle r-brio...
Running as unit: run-u160.service
Press ^] three times within 1s to disconnect TTY.
==> Erstelle Paket: r-brio 1.1.3-2 (Mi 22 Jun 2022 12:17:43 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Fehlende Abhängigkeiten:
  -> r-testthat
==> FEHLER: Konnte nicht alle Abhängigkeiten auflösen.

Probably a manjaro bug again?
I also tried manually to install -> r-testthat - same error message...
```

**Comment by sukanka** [comment]
> I updated on my main machine to 0.16.3 just fine. Now I try to install fresh on my laptop and get:
> 
> ```
> Erstelle r-brio...
> Running as unit: run-u160.service
> Press ^] three times within 1s to disconnect TTY.
> ==> Erstelle Paket: r-brio 1.1.3-2 (Mi 22 Jun 2022 12:17:43 CEST)
> ==> Prüfe Laufzeit-Abhängigkeiten...
> ==> Prüfe Buildtime-Abhängigkeiten...
> ==> Fehlende Abhängigkeiten:
>   -> r-testthat
> ==> FEHLER: Konnte nicht alle Abhängigkeiten auflösen.
> 
> Probably a manjaro bug again?
> I also tried manually to install -> r-testthat - same error message...
> ```

Oh, after you added a new repository to `pacman.conf`, please run `sudo pacman -Syy` to sync the databases first. (I guess you used `pacman` instead of `yay` or `paru`, since `yay` and `paru` can find these packages in AUR.) 

BTW, if you have further questions, you are welcome to open an issue at [BioArchLinux](https://github.com/BioArchLinux/Packages), since this has few things to do with jasp-desktop.
