### ISSUE TITLE
[Feature Request]: Tests other than Test 1 incorrectly being applied to the Moving Range Chart. 

### ISSUE THREAD

**Issue by RNE365** [jasp-stats/jasp-issues#2809]
### JASP Version

0.18.3

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Variable Charts for Individuals

### What OS are you seeing the problem on?

Windows 11

### Bug Description

[Simple XmR and Process Capability example.jasp.csv](https://github.com/user-attachments/files/16087927/Simple.XmR.and.Process.Capability.example.jasp.csv)
[Simple XmR and Process Capability example.pdf](https://github.com/user-attachments/files/16087928/Simple.XmR.and.Process.Capability.example.pdf)
![Screenshot 2024-07-03 173122](https://github.com/jasp-stats/jasp-issues/assets/147270953/0900d951-11e8-4f77-a42e-4473a3431020)

Only the first Western Electric signal detection rule (a point beyond the three sigma limits) applies to the Moving Range Chart.  

### Expected Behaviour

The only rule applied to the Moving Range Chart is Detection Rule 1: A point beyond the three sigma limits. 

### Steps to Reproduce

1. Produce an XmR chart using the data provided.
2. Observe that JASP is flagging Test 2 rules on the Moving Range Chart.
3. The same error/bug is also apparent when performing Process Capability Study.
![Screenshot 2024-07-03 173122](https://github.com/jasp-stats/jasp-issues/assets/147270953/729aff4b-1820-42b2-824f-6f7004b21b97)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
The next version (after 19.0) will be able to select which tests to apply, which should resolve this

**Comment by RNE365** [comment]
But the current version is manifestly wrong. I spoke with a manager yesterday who was pretty keen on JASP until one of his engineers pointed out the self same issue.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomtomme** [comment]
@RNE365 
That is why we have to thank you and everybody else who sends us these important bug reports!

**Comment by RNE365** [comment]
The world authority on process behaviour charts (control charts) is Donald Wheeler. He has highlighted various issues with AIAG statistical methods.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomtomme** [comment]
@JTPetter 
any news on this one?

I do not know what exactly is wrong but the error still seems valid for 0.19.2 beta.
jasp file:
[Simple.XmR.and.Process.Capability.example.jasp.zip](https://github.com/user-attachments/files/17492874/Simple.XmR.and.Process.Capability.example.jasp.zip)

**Comment by JTPetter** [comment]
Ah, looks like I was a little too optimistic about the timeline. But I am currently working on this

**Comment by tomtomme** [comment]
Candidate for 0.19.2 or 0.20?

**Comment by JTPetter** [comment]
0.20

**Comment by JTPetter** [comment]
With the linked PR, it will be possible to select which tests to apply to the charts. However, tests other than test 1 will still be applied to the MR chart if they are selected. This is the same behavior as in other software. Below an example from other software with the dataset linked in https://github.com/jasp-stats/jasp-issues/issues/3296. JASP gives the same results. If it is indeed wrong to apply tests other than test 1 to the MR chart I would need to see a reference for this, as it appears other software packages also do this.

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/31ec927f-ca47-4e53-87cc-d2c438c08073" />
