### ISSUE TITLE
[Bug]: Time Series Descriptives Error

### ISSUE THREAD

**Issue by stefanosolaroli** [jasp-stats/jasp-issues#3428]
### JASP Version

0.19.3

### JASP Module

Time Series

### What analysis are you seeing the problem on?

Time Series Descriptives

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Trying to plot a serie with YYYY-MM-DD hh:mm:ss data format the analisys is terminated unexpectedly and no graph is shown

### Expected Behaviour

graph should be plotted

### Steps to Reproduce

select time serie
select variable to plot
results do not show and a pop up appears with error

### Log (if any)

This analysis terminated unexpectedly.

Error in cor(dataset$y, yLag, use = 'complete.obs'): no complete element pairs

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.DescriptivesTimeSeries(jaspResults, dataset, options)

.tsDescriptivesTable(jaspResults, dataset, options, ready, position = 1, dependencies = c(.tsDescriptivesDependencies(), 'descriptivesTableTransposed'))

cor(dataset$y, yLag, use = 'complete.obs')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### More Debug Information

[Elab Dati Falda 21_03_25_BUG.zip](https://github.com/user-attachments/files/20036549/Elab.Dati.Falda.21_03_25_BUG.zip)

[Elab Dati Falda 21_03_25_BUG.zip](https://github.com/user-attachments/files/20036670/Elab.Dati.Falda.21_03_25_BUG.zip)

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@stefanosolaroli 
thx for the detailed report. I can replicate the error. The data seems to be fine, so this indeed seems to be a bug. 

@FBartos @sophieberkhout 
Any idea?

**Comment by FBartos** [comment]
I think that @hrgodmann is now maintaining the module

**Comment by tomtomme** [comment]
@hrgodmann 
Can you confirm? 

If yes @juliuspfadt , could you Update keywords.js accordingly? Thx

**Comment by juliuspfadt** [comment]
done

**Comment by juliuspfadt** [comment]
Were those comments nonsense or why did you delete them?

**Comment by tomtomme** [comment]
Very old without needed / relevant infos

**Comment by hrgodmann** [comment]
Hi All,
Thanks! I am taking care of the issue!

**Comment by tomtomme** [comment]
@hrgodmann 
just wanted to confirm that the error is still there.

-------- Application Info --------
JASP Version: JASP 0.95.1
Build Branch: HEAD
Build Date: Sep  8 2025 13:32:53 (Netherlands)
Last Commit: 180d14c18d13c107ee7c16b0993ff7e1cc02680b

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.8
Kernel Type: linux
Kernel Version: 6.12.44-3-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: de_DE

**Comment by tomtomme** [comment]
bug still there with current beta:
-------- Application Info --------
JASP Version: JASP 0.96
Build Branch: HEAD
Build Date: Feb 10 2026 17:10:55 (Netherlands)
Last Commit: 4cf656b45ccc9b10255895fe00a8cd673ae89567

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.10
Kernel Type: linux
Kernel Version: 6.18.8-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platform Name: wayland
System Local: de_DE

**Comment by tomtomme** [comment]
fixed data to reproduce - remove zip

[time.jasp.zip](https://github.com/user-attachments/files/28769410/time.jasp.zip)

@hrgodmann 
So there is something strange in the data - the last 3 time stamps are doubled:

<img width="951" height="839" alt="Image" src="https://github.com/user-attachments/assets/9e0c0471-fd1e-45f3-80ac-da28d4c31245" />

But even when I fix this, the error persists.

Even more strange:
The error does not occur with "predictive analytics" module, which essentially produces the same plot. And while it does not show the error,  the time variable seems to be ignored - the plot does not switch to displaying time stamps on the x-axis... strange.
The only module that handles this correctly is the "prophet" module.

<img width="1768" height="1157" alt="Image" src="https://github.com/user-attachments/assets/f453fe34-27fd-41d0-a5fd-e36050cf22c0" />

**Comment by Lachgast** [comment]
The bug (?) seems to be still present in version 0.98.1.

**Comment by tomtomme** [comment]
confirmed. Sry for taking so long!

**Comment by hrgodmann** [comment]
Thanks for the reminder! I will look into this in the next days! (originally hoped it would be solved with other changes we implemented, but that did not work out. So will try to fix this separately before 1.0 )

**Comment by Lachgast** [comment]
Hi hrgodmann and tomtomme! 
Looking into it would be much appreciated. I need to plot the mean of indoor temperatures by day on a time scale in days for a research that needs publication in a few days. I'm afraid the questionnaire program that I worked with (Qualtricks) does not allow for such an analysis.
If you need any additional dataset to work with, I'd be more than happy to share a data set to run some tests with. Anything that can help you progress your work.

Thank you very much!
