### ISSUE TITLE
Order of conditions is mixed up

### ISSUE THREAD

**Issue by jens-k** [jasp-stats/jasp-issues#362]
* JASP version: 0.9.2
* OS name and version: Windows 7
* Analysis: Repeated Measures ANOVA
* Bug description: When dragging variables into "repeated measures cells", the order of those variables is not retained but re-ordered alphabetically. 
* Add JASP files as a zip:
* Screenshot: 
Left: (data) the first variable of that group is "BIAS_baseline_wa". 
Right: After dragging them over to "repeated measures cells", the first variable is "BIAS_baseline_sl", presumably because it comes first alphabetically. This can really mess up your analysis.
![jasp](https://user-images.githubusercontent.com/10050167/58334591-28dba200-7e40-11e9-9d8b-2190f6ca75ab.png)
* Expected behaviour: Retain order of variables since most users will have arranged them in the most practical way.
* Steps to reproduce: 
Open a file with several variables, start a repeated measures ANOVA, drag several variables at once into "repeated measures cells". The order is not necessarily the same as in the original data.

**Comment by boutinb** [comment]
This is fixed with version 0.10.0

**Comment by jens-k** [comment]
Huh, that release is packed with a bunch of great new features and bug fixes. Thanks a lot!

**Comment by boutinb** [comment]
Thanks!

**Comment by cs726** [comment]
I have upgraded to version 0.10.0 and still have this same problem on MacOS High Sierra version 10.13.6.

**Comment by jens-k** [comment]
Still having the same problems with version 0.10 (on Windows 10), although only in particular cases:

List of variables:
![image](https://user-images.githubusercontent.com/10050167/60589855-c066d580-9d9a-11e9-8bbd-2bc15d440452.png)

After dragging over to Repeated Measures Cells:
![image](https://user-images.githubusercontent.com/10050167/60589877-d1afe200-9d9a-11e9-978c-fbcdcfd5bd82.png)

The prob does not occur with any of my other variables anymore, starting with TH_, SLOPE_, FIX_.
