### ISSUE TITLE
layout of sequential analysis in Bayesian A/B test is not right.

### ISSUE THREAD

**Issue by itremont** [jasp-stats/jasp-issues#883]
* JASP version: **013**

* OS name and version: **MacOS  Catalina version 10.15.6 (19G73)**
* Bug description: **Layout of sequential analysis is off: 1. Subheading "Prior Probabilities" is cut off; 2. Proportion wheel for posterior probabilities  is within legend. Not good for publication! 3. The xy graph also looks weird but I am not sure about its appearance. **
* Expected behaviour: 

#### Steps to reproduce:
1. Go to '..Summary Statistics' 
2. Click on '..Bayesian A/B test..'
3. Input: '..for group 1: 20 in successes, sample size 37; Group 2: 29 in successes, 36 in sample size...'
4. Tick on '..BF10, prior and posterior, sequential analysis..'
<img width="1503" alt="Screen Shot 2020-07-15 at 10 07 44 PM" src="https://user-images.githubusercontent.com/62923814/87622724-55f4af00-c6e9-11ea-9cda-b9a070920714.png">
<img width="534" alt="Screen Shot 2020-07-15 at 10 08 37 PM" src="https://user-images.githubusercontent.com/62923814/87622733-5b51f980-c6e9-11ea-8c91-9d23912cf66c.png">

.
**THANK YOU**

<img width="534" alt="Screen Shot 2020-07-15 at 10 08 37 PM" src="https://user-images.githubusercontent.com/62923814/87622769-69a01580-c6e9-11ea-8fce-b9814fa1e40d.png">
<img width="1503" alt="Screen Shot 2020-07-15 at 10 07 44 PM" src="https://user-images.githubusercontent.com/62923814/87622792-77ee3180-c6e9-11ea-8ba9-a5912bb08580.png">

**Comment by itremont** [comment]
BTW, apologize for repeating images.

**Comment by EJWagenmakers** [comment]
Thanks. I ran this on 0.13.1, under Windows, and it *does* give the desired result:
![image](https://user-images.githubusercontent.com/8603015/87769817-6a869380-c81e-11ea-927b-2965b05ad7ba.png)

@Akash, strange that the plots would change depending on the operating system! 
Also, @Akash, note that the input fields start with a "0". For some input fields in JASP, we want users to be able to input fractions, so "0.5". Here, the inputs are integers, and "020" should not really be valid input. It is accepted, and nothing bad seems to happen, but I do find it strange. @AlexanderLyNL : do we leave this as is or change it? If we change it, how?

**Comment by itremont** [comment]
Dear EJ:
Thanks for your comments. Yes, i did try on Windows, no problem at all.  This happens only on Mac, with the latest version of Catalina. I haven’t tried on older versions.

**Comment by itremont** [comment]
Gentlemen:
I tried on Linux Ubuntu 19.10 and I had a similar bug to MacOS. My impression is that things are made to work primarily for Windows.

**Comment by akashrajkn** [comment]
@EJWagenmakers I will take a look at this. I suspect the plots issue is due to the style restrictions in the abtest pacakge: `N.B.: This plot has been designed to look good in the following format: In inches, 530 / 72 (width) by 400 / 72 (height); in pixels, 530 (width) by 400 (height).`

**Comment by itremont** [comment]
Hi, Akash! Ivo here. I hoped issue #883 was fixed in version 0.14, but it is not included in the bug fix list. Am I correct? 
Greetings
Ivo

**Comment by boutinb** [comment]
@akashrajkn or @quentingronau: did you update the R package?

**Comment by akashrajkn** [comment]
@itremont on the Windows version, it has been fixed.

@boutinb The `abtest` package has to be updated for the flatpak version

**Comment by itremont** [comment]
Akash: This has never been a problem with Windows, only with Mac and Linux. Did you mean the layout works well now on Mac?
Thank you. Appreciate all the work you guys do.

**Comment by akashrajkn** [comment]
@boutinb abtest `v0.2.1` doesn't seem to fix the issue on Mac. Should we rewrite the abtest plots using ggplot2?

**Comment by quentingronau** [comment]
On my Mac this works fine... Also, there is now 0.2.2 but the changes
should not affect the plotting at all.

**Comment by juliuspf** [comment]
this seems fixed for Mac as well, so I will close it now. @itremont, feel free to reopen if the issue remains for you.
